### PR TITLE
fix(client/context-pad-provider): restrict context pad for labels

### LINKED ISSUE #104: Event labels provide context menu
__Describe the Bug__

__Steps to Reproduce__

// when
I click on an event label

// then
a context menu appears

zeebe_modeler_label_context

__Expected Behavior__

no context menu appears

__Environment__

 - OS: linux
 - Zeeber Modeler Version: 0.7.0-alpha2

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #104 

Kapture 2019-09-23 at 14 18 23

### CODE REVIEW

File: client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js [hunk 1]
```diff
@@ -65,6 +65,14 @@ describe('customs - context-pad', function() {
       });
     }
 
+
+    it('should not provide any entries for labels', inject(function() {
+
+      expectContextPadEntries('StartEvent_1_label', []);
```
Comment (oguzeroglu) [inline client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js]: This test does not fail even if you comment out the "**return filteredActions**" line in CustomContextPadProvider. The reason for this is that inside the **expectContextPadEntries** function test is performed for each **expectedEntries** variable which is an empty array in that case, so no test is performed. Instead of an empty array, a full list of context entries with **!** prefix should be passed:

An example would be: **['!append.append-service-task']**

Comment (pinussilvestrus) [reply client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js]: Thanks, will have a look.

Comment (pinussilvestrus) [reply client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js]: I updated the test case so that we definitely check _no_ entries are available for labels. It felt uncomfortable to me testing to _what's not included_ with the helper function. What we should test is that the context pad is indeed empty.

Comment (oguzeroglu) [reply client/src/app/tabs/bpmn/custom/__tests__/CustomContextPadProviderSpec.js]: Makes more sense, in fact much clearer solution than what I proposed :)
